sudo: required
services:
  - docker

before_install:
  - docker build -t guomq920418/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true guomq920418/docker-react npm run test

language: generic

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-462633564745"
  bucket_path: "docker-react"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

